import type { AppSettings, Job, Portal, Stats } from './types';

const now = Date.now();
const hoursAgo = (h: number) => new Date(now - h * 3_600_000).toISOString();
const daysAgo = (d: number) => new Date(now - d * 86_400_000).toISOString();

export const DEMO_JOBS: Job[] = [
  {
    id: 1,
    company: 'Anthropic',
    title: 'Staff Software Engineer · AI Platform',
    location: 'Remote (EMEA · IL friendly)',
    url: 'https://www.anthropic.com/careers',
    scraped_at: hoursAgo(3),
    posted_at: daysAgo(4),
    relevance_score: 94,
    tech_score: 96,
    experience_score: 92,
    geography_score: 90,
    brief:
      '- Direct stack overlap: Python, FastAPI, async, LLM inference infra.\n- Role scope (architect platform layer) matches seniority + 8y experience.\n- Remote-EMEA designation includes Israel — geography compliant.\n- Bonus: explicit RAG/agent evaluation work on the JD.',
    analyzed_at: hoursAgo(3),
    notified: true,
    dismissed: false,
    starred: true,
  },
  {
    id: 2,
    company: 'Wix',
    title: 'Senior Backend Engineer · Data Platform',
    location: 'Tel Aviv',
    url: 'https://www.wix.com/jobs',
    scraped_at: hoursAgo(3),
    posted_at: daysAgo(1),
    relevance_score: 88,
    tech_score: 90,
    experience_score: 86,
    geography_score: 100,
    brief:
      '- Strong Python + Kafka match; Postgres + Redis stack overlap.\n- Tel Aviv office — perfect geographic match.\n- Seniority bracket (5-8y) lands inside candidate range.\n- Minor gap: requires Scala which CV does not list.',
    analyzed_at: hoursAgo(3),
    notified: true,
    dismissed: false,
    starred: false,
  },
  {
    id: 3,
    company: 'Lightricks',
    title: 'AI Engineer · Generative Models',
    location: 'Jerusalem',
    url: 'https://www.lightricks.com/careers',
    scraped_at: hoursAgo(3),
    posted_at: daysAgo(2),
    relevance_score: 86,
    tech_score: 84,
    experience_score: 86,
    geography_score: 100,
    brief:
      '- LLM + diffusion model experience aligns with CV "AI agents" domain.\n- Jerusalem-based, IL geography satisfied.\n- Role wants PyTorch + research-paper-reading culture — candidate has it.\n- Slight scope mismatch: more research than platform work.',
    analyzed_at: hoursAgo(3),
    notified: true,
    dismissed: false,
    starred: false,
  },
  {
    id: 4,
    company: 'Vercel',
    title: 'Senior Full-Stack Engineer · Dashboard',
    location: 'Remote (Global)',
    url: 'https://vercel.com/careers',
    scraped_at: hoursAgo(4),
    posted_at: daysAgo(5),
    relevance_score: 84,
    tech_score: 95,
    experience_score: 82,
    geography_score: 60,
    brief:
      '- Stack is a direct mirror: TS, React, Next.js, Tailwind, FastAPI parallels.\n- Remote-global accepts IL but timezone overlap with SF is the gap.\n- Senior IC role matches scope.\n- Compensation likely USD-denominated — strong upside.',
    analyzed_at: hoursAgo(4),
    notified: true,
    dismissed: false,
    starred: true,
  },
  {
    id: 5,
    company: 'Monday.com',
    title: 'Tech Lead · Platform Infrastructure',
    location: 'Tel Aviv',
    url: 'https://monday.com/careers',
    scraped_at: hoursAgo(4),
    posted_at: daysAgo(3),
    relevance_score: 81,
    tech_score: 78,
    experience_score: 88,
    geography_score: 100,
    brief:
      '- Tech Lead scope (own a vertical, manage 3-5 ICs) is a stretch-fit.\n- Stack: Ruby-on-Rails primary, Python secondary — minor mismatch.\n- Tel Aviv HQ, geography ideal.\n- Strong career-growth optionality at scale.',
    analyzed_at: hoursAgo(4),
    notified: true,
    dismissed: false,
    starred: false,
  },
  {
    id: 6,
    company: 'Mobileye',
    title: 'Senior Software Architect · Perception',
    location: 'Jerusalem',
    url: 'https://www.mobileye.com/careers',
    scraped_at: hoursAgo(5),
    posted_at: daysAgo(6),
    relevance_score: 78,
    tech_score: 72,
    experience_score: 90,
    geography_score: 100,
    brief:
      '- Architect scope and seniority alignment is strong.\n- Stack skews C++/CUDA — CV is Python-primary, partial gap.\n- Jerusalem office, IL compliant.\n- Domain (autonomous vehicles) is adjacent, not direct.',
    analyzed_at: hoursAgo(5),
    notified: true,
    dismissed: false,
    starred: false,
  },
  {
    id: 7,
    company: 'Riskified',
    title: 'Staff Engineer · Risk Decisioning',
    location: 'Tel Aviv',
    url: 'https://www.riskified.com/careers',
    scraped_at: hoursAgo(6),
    posted_at: daysAgo(2),
    relevance_score: 76,
    tech_score: 75,
    experience_score: 78,
    geography_score: 100,
    brief:
      '- Staff IC scope — slightly above current seniority but plausible.\n- Python + ML infra match; Clojure as secondary is unfamiliar.\n- Tel Aviv HQ.\n- Fintech domain adjacent to prior fintech experience.',
    analyzed_at: hoursAgo(6),
    notified: true,
    dismissed: false,
    starred: false,
  },
  {
    id: 8,
    company: 'Outbrain',
    title: 'Backend Engineering Lead · Ads',
    location: 'Netanya',
    url: 'https://www.outbrain.com/careers',
    scraped_at: hoursAgo(7),
    posted_at: daysAgo(7),
    relevance_score: 71,
    tech_score: 68,
    experience_score: 78,
    geography_score: 90,
    brief:
      '- Lead role with people-management — stretch beyond current IC track.\n- Java/Kotlin primary, Python supplementary — meaningful stack gap.\n- Netanya is ~30min from Tel Aviv, geo acceptable.\n- Ad-tech domain not previously explored in CV.',
    analyzed_at: hoursAgo(7),
    notified: true,
    dismissed: false,
    starred: false,
  },
  {
    id: 9,
    company: 'Microsoft Israel',
    title: 'Principal Engineer · Azure AI',
    location: 'Herzliya',
    url: 'https://careers.microsoft.com',
    scraped_at: hoursAgo(8),
    posted_at: daysAgo(1),
    relevance_score: 68,
    tech_score: 70,
    experience_score: 60,
    geography_score: 100,
    brief:
      '- Principal level — 2 grades above current Senior position, low likelihood.\n- Tech stack aligned: Python, .NET, Azure AI services.\n- Herzliya office, IL geography ideal.\n- Worth applying as stretch but not high-confidence.',
    analyzed_at: hoursAgo(8),
    notified: false,
    dismissed: false,
    starred: false,
  },
  {
    id: 10,
    company: 'Pendo',
    title: 'Frontend Engineer · Growth',
    location: 'Raanana',
    url: 'https://www.pendo.io/careers',
    scraped_at: hoursAgo(9),
    posted_at: daysAgo(4),
    relevance_score: 52,
    tech_score: 70,
    experience_score: 40,
    geography_score: 100,
    brief:
      '- Frontend-only role — uses ~30% of CV breadth.\n- React + TS match strong, but missing backend ownership.\n- Mid-level scope (3-5y) below candidate seniority.\n- Geography ideal but role is a downgrade.',
    analyzed_at: hoursAgo(9),
    notified: false,
    dismissed: false,
    starred: false,
  },
];

export const DEMO_PORTALS: Portal[] = [
  {
    id: 1,
    name: 'Anthropic Careers',
    ats_type: 'greenhouse',
    board_url: 'https://boards.greenhouse.io/anthropic',
    company: 'Anthropic',
    is_active: true,
    last_scanned_at: hoursAgo(3),
    last_error: null,
    created_at: daysAgo(14),
  },
  {
    id: 2,
    name: 'Wix Jobs',
    ats_type: 'workday',
    board_url: 'https://wix.wd3.myworkdayjobs.com/Wix',
    company: 'Wix',
    is_active: true,
    last_scanned_at: hoursAgo(3),
    last_error: null,
    created_at: daysAgo(14),
  },
  {
    id: 3,
    name: 'Vercel Careers',
    ats_type: 'greenhouse',
    board_url: 'https://boards.greenhouse.io/vercel',
    company: 'Vercel',
    is_active: true,
    last_scanned_at: hoursAgo(4),
    last_error: null,
    created_at: daysAgo(14),
  },
  {
    id: 4,
    name: 'Monday.com',
    ats_type: 'greenhouse',
    board_url: 'https://boards.greenhouse.io/mondaycom',
    company: 'Monday.com',
    is_active: true,
    last_scanned_at: hoursAgo(4),
    last_error: null,
    created_at: daysAgo(7),
  },
  {
    id: 5,
    name: 'Lightricks',
    ats_type: 'lever',
    board_url: 'https://jobs.lever.co/lightricks',
    company: 'Lightricks',
    is_active: true,
    last_scanned_at: hoursAgo(3),
    last_error: null,
    created_at: daysAgo(7),
  },
];

export const DEMO_SETTINGS: AppSettings = {
  default_location: 'Israel',
  default_email: 'jackamichai@gmail.com',
  relevance_threshold: 75,
  scan_cron: '0 10 * * *',
  llm_provider: 'anthropic',
};

export const DEMO_STATS: Stats = {
  total_jobs: 142,
  scored_jobs: 142,
  high_match_jobs: 7,
  portals_active: 5,
  last_scan_at: hoursAgo(3),
};
